### ISSUE TITLE
`eslint-comments/require-description` should allow ignoring particular rules

### ISSUE THREAD

**Issue by tylerlaprade** [eslint-community/eslint-plugin-eslint-comments#134]
It's very nice that we can ignore categories of `eslint` directives. I would find it very helpful to also be able to ignore particular ESLint rules that we disable for self-evident reasons, such as importing a forbidden library is only allowed in our `ui-component` folder.

(cloned from https://github.com/mysticatea/eslint-plugin-eslint-comments/issues/76)

**Comment by mcongrove** [comment]
Ran into this need in my codebase; we have a variable we use throughout the app which causes a render-loop if we add it as a React hook dependency, so we ended up with quite a few `eslint-disable-next-line react-hooks/exhaustive-deps`. Having to add the same comment over and over in this case would be unnecessary, as everyone using the codebase understands why the rule is being disabled.

I've popped up a PR for this.

**Comment by tylerlaprade** [comment]
Thank you very much for the PR, @mcongrove! It sounds like your use case would be better served by a variable-name exclusion for that particular rule, though, so that the rule would still work on other variables.

**Comment by mcongrove** [comment]
> It sounds like your use case would be better served by a variable-name exclusion for that particular rule, though, so that the rule would still work on other variables.

I over-simplified a bit for the example; it's actually quite a few variables. It's probably indicative of a bigger issue in the libraries we choose and how we utilize hooks, but I'm just in charge of linting rules :)

**Comment by fregante** [comment]
> everyone using the codebase understands why the rule is being disabled

Do they? Developer memory is limited. At some point someone new will see the code and they won't have any context. Comments outlive developers.

**Comment by JoshuaKGoldberg** [comment]
Re-opening because a lack of maintainer response shouldn't cause an issue to be closed. And because I think this is a good thing to discuss now that there are more folks active in this repo. 🙂 

Personally, I agree fregante's comment. I don't think it's healthy to have _so many_ disables that you want to stop requiring descriptions. From my viewpoint, if a rule is giving a lot of reports you don't agree with, the likely scenarios are:

* The rule is not useful at all (perhaps in some files), and you should turn it off (perhaps just for those files)
* The rule has a bug: in which case the disable directives should link to the bug so future devs know why and not think it's reasonable to keep disabling things
* The rule is genuinely not applicable for that specific style of code: which is an odd one and likely deserves even more of an explanation

> `react-hooks/exhaustive-deps`

I'll also call out that _every single time_ I have seen this disabled, it was indicative of either a true bug or a non-idiomatic holding of React. The latter of which almost always caused the former.

So I'm -1 on this, but could be swayed if anybody could post a very compelling use case.
